version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=UserHub
    ports:
      - "5432:5432"
    networks:
      - mynetwork
  api:
    build:
      context: .
    ports:
      - "8080:8080" 
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=UserHub
      - POSTGRES_SSLMODE=disable
    depends_on: 
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
